# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Set up our JDK environment
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8
          
      - name: Run Kotlin Linter
        run: ./gradlew lint

      - name: Run Unit Tests
        run: ./gradlew test
        
      - name: Build all artifacts
        id: buildAllApks
        uses: eskatos/gradle-command-action@v1.3.3
        with:
          gradle-version: current
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
          arguments: assembleRelease
          
      - name: Codecov
        uses: codecov/codecov-action@v1.3.2
        with:
          # Repository upload token - get it from codecov.io. Required only for private repositories
          token: ee857b46-667a-48e9-a0c9-4e6d5791996c
          # User defined upload name. Visible in Codecov UI
          name: Dicoding-MADE
          # Specify the branch name
          override_branch: main
